### ISSUE TITLE
IEE754_binary32_encode doesn't work

### ISSUE THREAD

**Issue by ChrisIdema** [Daniel-Abrecht/IEEE754_binary_encoder#1]
The function "IEE754_binary32_encode" doesn't work; it always puts zeros in buffer.
Tested with several compilers.
Example: https://onlinegdb.com/jV8Cay4t2
I haven't tested the 64-bit functions.
It seems that comparing the exponent to -126 instead of 126 makes it work in most cases:
https://onlinegdb.com/CaotbdelLk
But it also fails with the value 0 as that one is stored as 0.5

**Comment by Daniel-Abrecht** [comment]
Interesting, now I'm unsure how that ever worked. It should work now, but there are still some things I'm unsure about, and it still has no test cases, so, use it at your own risk ;)
